version: '3.7'

services: 
    servers:
        container_name: micron_servers
        build: ./build
        ports:  
            - 80:80
            - 8081:8081
            - 6379:6379
        volumes:
            - ./www/:/var/www/
        
    database:
        image: mysql:5.7
        container_name: micron_database
        command: --default-authentication-plugin=mysql_native_password --sql_mode=''
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        depends_on:
            - servers
